import AppKit
import CoreGraphics
import Foundation
import Testing
@testable import Core

// SPEC §2 Weekend 1 DoD — observable test for the spine.
//
// > Press a hotkey → drag a region → release. Within a budget of
// > p95 ≤ 1.5s warm / ≤ 3.0s cold (first capture post-launch);
// > p50 ≤ 600ms warm — measured from hotkey-release to *both*
// > clipboard-write complete AND `.shot` package `fsync` returned —
// > a PNG of the selection is on the clipboard AND a `.shot` package
// > exists at `~/.shotfuse/library/<timestamp>_<bundle>.shot/` containing:
// >   - master.png at native resolution
// >   - ocr.json (wrapper per §6.3)
// >   - context.json
// >   - thumb.jpg at 256px
// >   - manifest.json with valid id (UUIDv7), created_at, expires_at = created + 24h, pinned: false
// >
// > Cmd+Shift+G opens a search overlay. Typing OCR text or a frontmost app
// > name returns the matching capture within 100ms.
// > A background launch agent (§15.1) deletes unpinned packages past expires_at.
//
// We drive the production CaptureCoordinator + RealFinalizing + LibraryIndex
// + ClipboardWriter + FusePolicy paths. Only the UI-bound
// RegionSelecting/ScreenCapturing collaborators are stubbed (canned frame +
// canned selection). This keeps the harness portable — no TCC Screen
// Recording grant, no real hotkey — while still exercising every component
// the latency budget actually pays for.

@Suite("Weekend 1 DoD")
struct WeekendOneDoDTests {

    // MARK: - Test 1: artifact shape

    @Test("End-to-end capture writes a .shot/ with all required artifacts and a valid manifest")
    func endToEndCaptureWritesShotPackageWithRequiredArtifacts() async throws {
        let env = try await DoDFixtures.makeEnv()
        defer { env.tearDown() }

        DoDFixtures.clearPasteboard()

        let url = try await env.coordinator.captureRegion()

        #expect(url.pathExtension == "shot")
        #expect(url.deletingLastPathComponent().standardizedFileURL == env.libraryRoot.standardizedFileURL)
        #expect(FileManager.default.fileExists(atPath: url.path))

        for required in ["master.png", "ocr.json", "context.json", "thumb.jpg", "manifest.json"] {
            let f = url.appendingPathComponent(required)
            #expect(
                FileManager.default.fileExists(atPath: f.path),
                "missing \(required) in \(url.lastPathComponent)"
            )
        }

        let manifestData = try Data(contentsOf: url.appendingPathComponent("manifest.json"))
        let manifest = try JSONDecoder().decode(Manifest.self, from: manifestData)

        // SPEC §2: manifest carries a valid UUIDv7. The on-disk filename is
        // also a UUIDv7 generated by CaptureCoordinator, but the two are
        // independently generated and not required to match.
        #expect(DoDFixtures.isValidUUIDv7(manifest.id), "manifest.id is not a valid UUIDv7: \(manifest.id)")
        let dirID = url.deletingPathExtension().lastPathComponent
        #expect(DoDFixtures.isValidUUIDv7(dirID), "directory id is not a valid UUIDv7: \(dirID)")
        #expect(manifest.pinned == false)
        #expect(manifest.master.path == "master.png")
        #expect(manifest.master.width > 0)
        #expect(manifest.master.height > 0)
        #expect(manifest.spec_version == 1)

        let iso = ISO8601DateFormatter()
        iso.formatOptions = [.withInternetDateTime, .withFractionalSeconds]
        let createdAt = iso.date(from: manifest.created_at)
            ?? ISO8601DateFormatter().date(from: manifest.created_at)
        #expect(createdAt != nil, "created_at must be ISO 8601: \(manifest.created_at)")

        let expiresAtString = try #require(manifest.expires_at, "expires_at must be present")
        let expiresAt = iso.date(from: expiresAtString)
            ?? ISO8601DateFormatter().date(from: expiresAtString)
        let expires = try #require(expiresAt, "expires_at must be ISO 8601: \(expiresAtString)")
        let created = try #require(createdAt)
        let delta = expires.timeIntervalSince(created)
        #expect(
            abs(delta - CaptureFinalization.defaultFuseInterval) < 1.0,
            "expires_at must be created_at + 24h (got \(delta)s)"
        )

        // Clipboard contract: PNG of the capture is on the pasteboard by the
        // time captureRegion() returns. CaptureCoordinator.swift:389 calls
        // ClipboardWriter.copyMaster after fsync.
        let pb = NSPasteboard.general
        let pngData = try #require(
            pb.data(forType: .png),
            "pasteboard must have a PNG payload after capture"
        )
        let nsImage = try #require(NSImage(data: pngData), "pasteboard PNG must decode")
        #expect(nsImage.size.width > 0)
        #expect(nsImage.size.height > 0)
    }

    // MARK: - Test 2: warm latency

    @Test("Warm capture latency: p50 ≤ 600ms, p95 ≤ 1500ms over 30 samples")
    func warmCaptureLatencyMeetsBudget() async throws {
        let env = try await DoDFixtures.makeEnv()
        defer { env.tearDown() }

        // Warm-up: one un-measured capture so SQLite WAL is primed,
        // pasteboard handle is hot, FS caches are loaded.
        _ = try await env.coordinator.captureRegion()

        var samples: [TimeInterval] = []
        samples.reserveCapacity(30)
        for _ in 0..<30 {
            let start = ContinuousClock.now
            _ = try await env.coordinator.captureRegion()
            let elapsed = ContinuousClock.now - start
            samples.append(DoDFixtures.seconds(elapsed))
        }

        let sorted = samples.sorted()
        let p50 = DoDFixtures.percentile(0.50, ofSorted: sorted)
        let p95 = DoDFixtures.percentile(0.95, ofSorted: sorted)

        #expect(p50 <= 0.600, "p50 warm = \(p50)s exceeds 600ms budget")
        #expect(p95 <= 1.500, "p95 warm = \(p95)s exceeds 1.5s budget")
    }

    // MARK: - Test 3: cold latency

    @Test("Cold capture latency: first capture post-launch ≤ 3000ms")
    func coldCaptureLatencyMeetsBudget() async throws {
        // Fresh environment = fresh CaptureCoordinator + fresh LibraryIndex
        // (forces SQLite open + schema migration). No warm-up.
        let env = try await DoDFixtures.makeEnv()
        defer { env.tearDown() }

        let start = ContinuousClock.now
        _ = try await env.coordinator.captureRegion()
        let elapsed = DoDFixtures.seconds(ContinuousClock.now - start)

        #expect(elapsed <= 3.000, "cold capture = \(elapsed)s exceeds 3s budget")
    }

    // MARK: - Test 4: search latency

    @Test("Search overlay query returns matching capture within 100ms on a 1000-row index")
    func searchOverlayReturnsMatchUnderHundredMs() async throws {
        let tmp = try DoDFixtures.makeTmpDir()
        defer { DoDFixtures.cleanup(tmp) }

        let index = try LibraryIndex(databaseURL: tmp.appendingPathComponent("index.db"))
        defer { Task { await index.close() } }

        let apps = [
            "com.apple.dt.Xcode",
            "com.microsoft.VSCode",
            "md.obsidian",
            "com.apple.Safari",
            "com.tinyspeck.slackmacgap",
        ]
        let titleWords = [
            "ContentView", "AppDelegate", "Router", "LibraryIndex",
            "ScreenCaptureKit", "CaptureEngine", "manifest", "telemetry",
            "Shotfuse", "README",
        ]
        let ocrCorpus = [
            "the quick brown fox jumps over the lazy dog",
            "Shotfuse captures pixels and AX tree snapshots",
            "SwiftUI cannot own SCStream or SCStreamOutput",
            "master png is written once and never modified",
            "FTS5 external content tables index full text",
        ]

        for i in 0..<1000 {
            let id = String(format: "cap-%05d", i)
            let rec = LibraryRecord(
                id: id,
                createdAt: Int64(1_700_000_000 + i),
                expiresAt: Int64(1_700_000_000 + i + 24 * 3600),
                pinned: false,
                bundleID: apps[i % apps.count],
                windowTitle: "\(titleWords[i % titleWords.count])-\(i).swift",
                fileURL: "file:///Users/dev/proj/Sources/row\(i).swift",
                gitRoot: nil,
                browserURL: nil,
                clipboard: ocrCorpus[i % ocrCorpus.count],
                ocrText: "row\(i) marker\(i % 19) \(ocrCorpus[(i + 2) % ocrCorpus.count])"
            )
            try await index.insert(rec)
        }

        // SPEC §2: "Typing OCR text or a frontmost app name returns the
        // matching capture within 100ms." Cover three realistic queries:
        // OCR token, app/bundle word, file-path stem.
        let queries = ["marker7", "Xcode", "row512.swift"]

        for raw in queries {
            let sanitized = SearchQuery.sanitize(raw)
            // Run 5× and take the worst sample — the spec is a wall-time
            // bound, not a percentile.
            var worst: TimeInterval = 0
            var hits: [String] = []
            for _ in 0..<5 {
                let start = ContinuousClock.now
                hits = try await index.searchIDs(sanitized)
                let elapsed = DoDFixtures.seconds(ContinuousClock.now - start)
                worst = max(worst, elapsed)
            }
            #expect(!hits.isEmpty, "query '\(raw)' returned no hits")
            #expect(worst <= 0.100, "query '\(raw)' worst latency = \(worst)s exceeds 100ms")
        }
    }

    // MARK: - Test 5: fuse-gc

    @Test("fuse-gc deletes expired unpinned packages and keeps pinned + fresh ones")
    func fuseGCDeletesExpiredUnpinnedOnly() throws {
        let lib = try DoDFixtures.makeTmpDir()
        defer { DoDFixtures.cleanup(lib) }

        let now = Date(timeIntervalSince1970: 1_800_000_000)
        let oneHourAgo = now.addingTimeInterval(-3600)
        let oneHourAhead = now.addingTimeInterval(3600)

        let expiredUnpinned = lib.appendingPathComponent("expired-unpinned.shot", isDirectory: true)
        let expiredPinned = lib.appendingPathComponent("expired-pinned.shot", isDirectory: true)
        let freshUnpinned = lib.appendingPathComponent("fresh-unpinned.shot", isDirectory: true)

        try DoDFixtures.writeFakeShotPackage(at: expiredUnpinned, expiresAt: oneHourAgo, pinned: false)
        try DoDFixtures.writeFakeShotPackage(at: expiredPinned, expiresAt: oneHourAgo, pinned: true)
        try DoDFixtures.writeFakeShotPackage(at: freshUnpinned, expiresAt: oneHourAhead, pinned: false)

        let result = try FusePolicy().collect(libraryRoot: lib, now: now)

        #expect(result.deleted.map(\.lastPathComponent) == [expiredUnpinned.lastPathComponent])
        #expect(result.skippedPinned.map(\.lastPathComponent) == [expiredPinned.lastPathComponent])
        #expect(result.errors.isEmpty)

        let fm = FileManager.default
        #expect(!fm.fileExists(atPath: expiredUnpinned.path), "expired unpinned must be gone")
        #expect(fm.fileExists(atPath: expiredPinned.path), "pinned must be kept")
        #expect(fm.fileExists(atPath: freshUnpinned.path), "fresh unpinned must be kept")
    }
}

// MARK: - Fixtures

private struct DoDEnv {
    let root: URL
    let libraryRoot: URL
    let witnessesRoot: URL
    let index: LibraryIndex
    let coordinator: CaptureCoordinator

    func tearDown() {
        Task { await index.close() }
        try? FileManager.default.removeItem(at: root)
    }
}

private enum DoDFixtures {

    static func makeEnv() async throws -> DoDEnv {
        let root = try makeTmpDir()
        let libraryRoot = root.appendingPathComponent("library", isDirectory: true)
        let witnessesRoot = root.appendingPathComponent("witnesses", isDirectory: true)
        try FileManager.default.createDirectory(at: libraryRoot, withIntermediateDirectories: true)

        let index = try LibraryIndex(databaseURL: root.appendingPathComponent("index.db"))

        let selector = StubRegionSelecting(canned: selection())
        let capturer = StubScreenCapturing(frame: capturedFrame())
        let coordinator = CaptureCoordinator(
            regionSelector: selector,
            screenCapturer: capturer,
            finalizer: RealFinalizing(),
            indexer: RealLibraryIndexing(index: index),
            libraryRoot: libraryRoot,
            witnessesRoot: witnessesRoot,
            contextProvider: {
                CaptureFinalization.Context(
                    frontmostBundleID: "com.example.dod",
                    frontmostWindowTitle: "DoD Test Window",
                    axAvailable: false
                )
            }
        )

        return DoDEnv(
            root: root,
            libraryRoot: libraryRoot,
            witnessesRoot: witnessesRoot,
            index: index,
            coordinator: coordinator
        )
    }

    static func makeTmpDir() throws -> URL {
        let url = FileManager.default.temporaryDirectory
            .appendingPathComponent("dod-\(UUID().uuidString)", isDirectory: true)
        try FileManager.default.createDirectory(at: url, withIntermediateDirectories: true)
        return url
    }

    static func cleanup(_ url: URL) {
        try? FileManager.default.removeItem(at: url)
    }

    static func clearPasteboard() {
        NSPasteboard.general.clearContents()
    }

    // MARK: - CapturedFrame builders

    static func display(id: CGDirectDisplayID = 1) -> DisplayMetadata {
        DisplayMetadata(
            id: id,
            nativeWidth: 3024,
            nativeHeight: 1964,
            nativeScale: 2.0,
            vendorID: nil,
            productID: nil,
            serial: nil,
            localizedName: "DoD Test",
            globalFrame: CGRect(x: 0, y: 0, width: 1512, height: 982)
        )
    }

    static func selection() -> RegionSelection {
        RegionSelection(
            rect: CGRect(x: 0, y: 0, width: 320, height: 200),
            display: display()
        )
    }

    /// 320×200 solid-grey CGImage. Realistic enough that PNG/JPEG encoding
    /// produces non-trivial bytes, small enough that 30 captures finish
    /// well under the warm budget.
    static func solidImage(width: Int = 320, height: Int = 200) -> CGImage {
        let bytesPerRow = width * 4
        var pixels = [UInt8](repeating: 0x7F, count: bytesPerRow * height)
        let cs = CGColorSpace(name: CGColorSpace.sRGB)!
        let ctx = pixels.withUnsafeMutableBufferPointer { buf -> CGContext in
            CGContext(
                data: buf.baseAddress,
                width: width,
                height: height,
                bitsPerComponent: 8,
                bytesPerRow: bytesPerRow,
                space: cs,
                bitmapInfo: CGImageAlphaInfo.premultipliedLast.rawValue
            )!
        }
        return ctx.makeImage()!
    }

    static func capturedFrame() -> CapturedFrame {
        CapturedFrame(
            image: solidImage(),
            pixelBounds: CGRect(x: 0, y: 0, width: 320, height: 200),
            display: display(),
            capturedAt: Date()
        )
    }

    // MARK: - Fake .shot/ package writer (for fuse-gc test)

    /// Writes a minimal `.shot/` directory with just a manifest carrying
    /// `expires_at` and `pinned`. FusePolicy only consults those two
    /// fields (Core/Sources/Core/Fuse/FusePolicy.swift:58-60), so the
    /// missing master.png/ocr.json/etc. don't matter for this test.
    /// Validates a UUIDv7 string per RFC 9562 §5.7: 8-4-4-4-12 lowercase hex
    /// with version nibble = 7 in the third group's first character and
    /// variant bits = 10 (high bits of the fourth group's first nibble in
    /// {8, 9, a, b}).
    static func isValidUUIDv7(_ s: String) -> Bool {
        guard UUID(uuidString: s) != nil else { return false }
        let parts = s.lowercased().split(separator: "-")
        guard parts.count == 5 else { return false }
        guard parts[2].first == "7" else { return false }
        let variant = parts[3].first.map(String.init) ?? ""
        return ["8", "9", "a", "b"].contains(variant)
    }

    static func writeFakeShotPackage(at url: URL, expiresAt: Date, pinned: Bool) throws {
        let fm = FileManager.default
        try fm.createDirectory(at: url, withIntermediateDirectories: false)
        let manifest: [String: Any] = [
            "id": UUID().uuidString,
            "expires_at": expiresAt.formatted(.iso8601),
            "pinned": pinned,
        ]
        let data = try JSONSerialization.data(withJSONObject: manifest, options: [.sortedKeys])
        try data.write(to: url.appendingPathComponent("manifest.json"))
    }

    // MARK: - Latency math

    static func seconds(_ d: Duration) -> TimeInterval {
        let comps = d.components
        return TimeInterval(comps.seconds) + TimeInterval(comps.attoseconds) / 1e18
    }

    /// Linear-interpolation percentile on a pre-sorted ascending array.
    /// Matches the "nearest-rank with interpolation" definition used in
    /// most monitoring tools (Prometheus quantile, Grafana p95, etc).
    static func percentile(_ p: Double, ofSorted samples: [TimeInterval]) -> TimeInterval {
        precondition(!samples.isEmpty)
        if samples.count == 1 { return samples[0] }
        let rank = p * Double(samples.count - 1)
        let lo = Int(rank.rounded(.down))
        let hi = Int(rank.rounded(.up))
        if lo == hi { return samples[lo] }
        let frac = rank - Double(lo)
        return samples[lo] + (samples[hi] - samples[lo]) * frac
    }
}

// MARK: - Stubs

private struct StubRegionSelecting: RegionSelecting {
    let canned: RegionSelection
    func select() async throws -> RegionSelection? { canned }
}

private struct StubScreenCapturing: ScreenCapturing {
    let frame: CapturedFrame
    func captureRegion(selection: RegionSelection) async throws -> CapturedFrame { frame }
    func captureWindow(pid: pid_t, windowID: CGWindowID, includeChildren: Bool) async throws -> CapturedFrame { frame }
    func captureFullscreen(displayID: CGDirectDisplayID) async throws -> CapturedFrame { frame }
}
